set export
FLASK_DEBUG := 'True'
FLASK_APP := '.'

test:
	flask run --host=127.0.0.1 --port=3000

# ssh tunnel to dev container to allow viewing the flask webUI on your local machine
ssh:
	ssh -L 3000:127.0.0.1:3000 dev
