set dotenv-load

serve:
	flask run --host=127.0.0.1 --port=3000

# ssh tunnel to dev container to allow viewing the flask webUI on your local machine
ssh:
	autossh -M 3001 -L 3000:localhost:3000 -N dev
